# Site Settings
title: "Develbyte"
name: "Narendra Dubey"
description: "Technology Enthusiast sharing insights on Data Science, AI, Python, and more."
url: "https://develbyte.github.io"
baseurl: ""

# Theme: Custom minimal design
# remote_theme: none

# Author information
author:
  name: "Narendra Dubey"
  email: "iamnarendradubey@gmail.com"
  bio: "Technology Enthusiast, Coder, Data Science enthusiast, AI explorer. I love talking to computers and sharing knowledge about Python, JavaScript, and data processing."
  location: "Bangalore"
  github: "im-naren"
  linkedin: "im-naren"
  stackoverflow: "2944691/imbatman"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

# Pagination
paginate: 5
paginate_path: /page:num/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE.txt
  - Rakefile
  - package.json
  - banner.js

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
      share: false
  - scope:
      path: ""
      type: pages
    values:
      layout: default